### ISSUE TITLE
Doubts about filters

### ISSUE THREAD

**Issue by carhermo** [iccmr-plymouth/Quantum-BCI#1]
Hey Satvik, Carlos here.

I'm having trouble running your code so I did my own version.
I would like it if you could take a look and tell me if there is something wrong.
I uploaded my notebook in 'carlos' branch so I don't mess up your 'main' branch.
Have a nice day.
Carlos.

**Comment by satvik-venkatesh** [comment]
Hi Carlos,

I think the filtering looks correct. Could we both have a zoom call sometime this week? It would be easier to discuss the alpha wave calculation over a call instead of typing. Let me know.

Thanks,
Satvik
